export default {
  ENTERPRISE: {
    REQUEST_GET_ALL: 'REQUEST_GET_ALL',
    SUCCESS_GET_ALL: 'SUCCESS_GET_ALL',
    FAILURE_GET_ALL: 'FAILURE_GET_ALL',
  },
  LOGIN: {
    REQUEST_SET_CREDENTIALS: 'REQUEST_SET_CREDENTIALS',
    SUCCESS_SET_CREDENTIALS: 'SUCCESS_SET_CREDENTIALS',
    FAILURE_SET_CREDENTIALS: 'FAILURE_SET_CREDENTIALS',
    REQUEST_LOGOUT: 'REQUEST_LOGOUT',
    SUCCESS_LOGOUT: 'SUCCESS_LOGOUT',
    FAILURE_LOGOUT: 'FAILURE_LOGOUT',
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    SUCCESS_LOGIN: 'SUCCESS_LOGIN',
    FAILURE_LOGIN: 'FAILURE_LOGIN',
  },
};
